package-lock.json
src/pages/BookmarkPage/BookmarkPage.jsx
src/pages/BookmarkPage/BookmarkPage.style.jsx
yarn.lock

close #21
<br />
북마크 페이지 제작입니다.
검색, 나열순서 선택, 앨범 목록이 출력되도록 하였습니다.
<br />
<br />

#21 [FEAT] 북마크 페이지 제작

---

package.json
src/apis/album.js
src/axios/index.js
src/constants/sort.js
src/main.jsx
src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
yarn.lock

close #36
<br />
- 앨범 리스트 조회 API 연결
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/4ea07868-3a90-48fd-9e4e-57aa6ad07a47"> |
| 사용자의 앨범 리스트 페이지 |
<br />
- API 호출 로직은 `src/apis` 아래에 작성해주세요.
- 리액트 쿼리 사용해서 서버 데이터 캐싱했습니다.
- 테스트하면서 사용한 계정에 더미 데이터가 완전히 쌓이지 않아서 화면엔 사진 하나만 보이는게 정상입니다.

#36 [FEAT] 앨범 리스트 조회 API 연결

---

src/apis/album.js
src/components/AlbumInfo/AlbumInfo.jsx
src/components/AlbumViewer/AlbumViewer.jsx
src/hooks/useAuth.jsx
src/main.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
src/route.jsx
src/utils/convertDate.js
src/utils/formatNumber.js

close #43
<br />
- 앨범 상세 API 연결
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/b2383511-720c-45f6-8545-25c67783d66c"> |
| 내 앨범 상세 페이지 | 
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/a09d995f-a8b8-4b33-a635-57456e93846f"> |
| 다른 사람의 앨범 상세 페이지 |

#43 [FEAT] 앨범 상세 조회 API 연결

---

src/components/AlbumViewer/AlbumViewer.jsx
src/components/AlbumViewer/AlbumViewer.style.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.style.jsx

close #39
<br />
- 앨범 상세 페이지에 수정 및 삭제 버튼이 없어 추가했습니다.
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/004c2c3f-7a80-4701-9472-7aef4c6e5e56"> |
| 앨범 상세 페이지 |

#39 [STYLE] 앨범 상세 페이지에 수정, 삭제 버튼 추가

---

src/apis/album.js
src/components/AlbumDetail/AlbumDetail.jsx
src/components/Chatting/Chatting.jsx
src/components/UserInfo/UserInfo.jsx
src/hooks/useAuth.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/route.jsx

close #41
<br />
- 앨범 삭제 API 연결
<br />
| <img width="710" alt="image" src="https://github.com/user-attachments/assets/5fa56247-ae7a-45a7-bb7b-7ec7a90d306b"> |
| 앨범 삭제 200 OK |
<br />
- 상혁님 PR 머지에 충돌 코드가 남아 있어서 해결했습니다.

#41 [FEAT] 앨범 삭제 API 연결

---

src/pages/FriendPage/FriendPage.jsx
src/pages/FriendPage/FriendPage.style.jsx

close #50
<br />
- 친구 페이지 마크업 및 스타일링
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/1d218505-2c35-408e-b47a-aafa2d8a8ff4"> |
| 친구 페이지 |

#50 [FEAT] 친구 페이지 UI

---

src/apis/friend.js
src/components/Avatar/Avatar.jsx
src/components/RandomFriend/RandomFriend.jsx
src/pages/FriendPage/FriendPage.jsx

close #52
<br />
- 친구 목록 조회 API 연결 
<br />
| <img width="559" alt="image" src="https://github.com/user-attachments/assets/cb658361-3f1e-4b6f-88b2-68641176b320"> |
| 친구 목록 조회 API 연결 200 OK |

#52 [FEAT] 친구 목록 조회 API 연결

---

src/axios/index.js

close #55
<br />
- 서버 도메인 환경변수로 전환
<br />
- 서버 도메인을 환경변수로 변환했습니다. `/` 바로 아래에 `.env` 파일 생성 후 아래 환경변수 추가해주세요.
- `VITE_SERVER_DOMAIN=서버도메인`

#55 [CHORE] 서버 도메인 환경변수로 전환

---

src/axios/index.js

#59 [MERGE] 개발 브랜치에서 배포 브랜치로 머지

---

netlify.toml
src/components/Chatting/Chatting.jsx

close #61
<br />
- netlify.toml 추가
- Chatting.jsx에서 스타일 컴포넌트 import 파일명 수정

#61 [FIX] 배포 오류 수정

---

netlify.toml
src/components/Chatting/Chatting.jsx

#59 [MERGE] 개발 브랜치를 배포 브랜치로 머지 

---

src/components/Chatting/Chatting.jsx

close #61
<br />
- 채팅 스타일 컴포넌트 import 경로명 오타 수정

#61 [FIX] 채팅 스타일 컴포넌트 경로 오타 수정

---

netlify.toml
src/components/Chatting/Chatting.jsx

#59 [MERGE] 배포 브랜치로 머지

---

netlify.toml

close #61
<br />
- 빌드 폴더명 dist로 정정

#61 [FIX] 빌드 폴더명 정정

---

src/apis/friend.js
src/pages/FriendPage/FriendList/FriendList.jsx
src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx

400 토큰 에러 발생
close #73
<br />
- 친구 삭제 API 연결
<br />
- 400 에러 발생
- 토큰이 확인이 안 되는 것 같습니다

#73 [FEAT] 친구 삭제 API 연결

---

src/pages/LoginPage/LoginPage.jsx

close #76
<br />
토큰 관련 코드 수정
<br />
<br />

[MODIFY] 토큰 관련 코드 수정

---

src/apis/friend.js

토큰 오류도 함께 해결
close #73
<br />
- 친구 삭제 API 스펙 변경

#73 [MODIFY] 친구 삭제 API 스펙 변경

---

src/apis/addInfo.js
src/apis/deleteAccount.js
src/apis/nickname.js
src/axios/index.js
src/pages/AddInfoPage/AddInfoPage.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/SetNicknamePage/SetNicknamePage.jsx
src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.style.jsx

close #79
<br />
<br />
<br />

#79 [FEAT] 로그인 토큰 문제 수정

---

src/apis/friend.js
src/components/Profile/Profile.jsx
src/components/Profile/Profile.style.jsx
src/components/RandomFriend/RandomFriend.jsx
src/hooks/useFriend.jsx
src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
src/pages/FriendPage/FriendList/FriendList.jsx
src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
src/pages/FriendPage/FriendSentList/FriendSentList.jsx

close #82
<br />
- 사용자 닉네임, 친구 상태 연동

#82 [FEAT] Profile 컴포넌트에 서버 데이터 연결

---

src/apis/album.js
src/assets/icons/icon.svg
src/components/Feed/Feed.jsx
src/components/Feed/FeedItem.jsx
src/dummy/images/index.js
src/hooks/usePagination.jsx
src/pages/MainPage/MainPage.jsx
src/pages/MainPage/MainPage.style.jsx

close #84
<br />
- 홈 게시글 리스트 API 연결

#84 [FEAT] 홈 게시글 리스트 API 연결

---

package-lock.json
src/components/AlbumDetail/AlbumDetail.jsx
src/components/AlbumDetail/CommentSection.jsx
src/components/Feed/CommentSection.jsx
src/components/Feed/FeedItem.jsx
src/pages/BookmarkPage/BookmarkPage.jsx
yarn.lock

close #87
<br />
게시글, 댓글, 대댓글 좋아요 기능 구현
<br />
<br />

게시글, 댓글, 대댓글 좋아요 기능 구현

---

src/main.jsx

close #90 
<br />
- 서버 통신 에러 메시지를 alert으로 띄워줌

#90 [FEAT] axios 에러를 제일 상위에서 핸들링

---

src/apis/album.js
src/components/AlbumMaking/index.js
src/components/Edit/Edit.jsx
src/components/Edit/Edit.style.jsx
src/components/Edit/index.js
src/components/Profile/Profile.jsx
src/components/Profile/Profile.style.jsx
src/constants/index.js
src/constants/scope.js
src/hooks/useAuth.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/pages/AlbumEditPage/AlbumEditPage.jsx
src/pages/AlbumEditPage/AlbumEditPage.style.jsx
src/pages/AlbumEditPage/index.js
src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
src/route.jsx

close #68
<br />
- 앨범 수정 API 연결

#68 [FEAT] 앨범 수정 API 연결

---

src/main.jsx

close #93
<br />
- 서버 응답 코드 404 핸들링

#93 [FEAT] 서버 404 응답 코드 핸들링

---

yarn.lock

[CHORE] yarn.lock

---

src/hooks/useAuth.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/route.jsx

[FIX] 앨범 상세 userId -> nickname

---

src/pages/AlbumPage/AlbumPage/AlbumPage.jsx

[FIX] useInfiniteScroll을 usePagination으로 교체

---

src/App.jsx
src/apis/addInfo.js
src/apis/deleteAccount.js
src/apis/nickname.js
src/components/Feed/Feed.style.jsx
src/components/Profile/Profile.jsx
src/components/RandomFriend/RandomFriend.jsx
src/components/Sidebar/Sidebar.jsx
src/hooks/useAuth.jsx
src/main.jsx
src/pages/AddInfoPage/AddInfoPage.jsx
src/pages/AlbumDetailPage/AlbumDetailPage.jsx
src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
src/pages/FriendPage/FriendList/FriendList.jsx
src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
src/pages/FriendPage/FriendSentList/FriendSentList.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.style.jsx
src/pages/MainPage/MainPage.jsx
src/pages/MainPage/MainPage.style.jsx
src/pages/PwdSearchPage/PwdSearchPage.jsx
src/pages/SetNicknamePage/SetNicknamePage.jsx
src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx

close #103 
<br />
데모데이 당일 수정했던 코드 + 탈퇴 기능을 추가로 구현하여 pr합니다!
- useAuth 코드 수정 -> isLogin, handleLogout, handleLogin, id, nickname을 받아올 수 있게 되었습니다
- 탈퇴 기능 구현 완료 -> '삭제합니다'를 입력하면 탈퇴가 완료됩니다. 
- 자동 로그인 기능을 구현하였습니다! 
- 로그인 페이지 스타일링을 수정했습니다.
<br />

[FEAT] useAuth.js 코드 수정, 탈퇴 기능, 자동 로그인 기능 구현

---

src/components/Feed/FeedItem.jsx

handleCommentHeart 가 주석 처리되어 있어 홈 화면 로딩에 문제가 발생해 수정합니다!
close #
<br />
<br />
<br />

[MODIFY] FeedItem.jsx handleCommentHeart 주석 처리 문제 수정

---

src/components/Feed/FeedItem.jsx

handleReplyHeart 코드가 잘려 있어 추가합니다
close #
<br />
<br />
<br />

[MODIFY] FeedItem.jsx handleReplyHeart 코드 추가

---

src/apis/certificationCode.js
src/apis/getMyProfile.js
src/apis/nickname.js
src/hooks/useAuth.jsx
src/pages/AddInfoPage/AddInfoPage.jsx
src/pages/AgreePage/AgreePage.jsx
src/pages/LoginPage/handleSocialLogin.jsx
src/pages/PwdSearchPage/PwdSearchPage.jsx
src/pages/RegisteredPage/RegisteredPage.jsx
src/pages/SetNicknamePage/SetNicknamePage.jsx
src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
src/pages/SignUpPage/SignUpPage.jsx

- api 수정에 따라 비밀번호 찾기 페이지, 회원가입 페이지에서 인증번호 전송하는 코드를 수정하였습니다!
- 프로필 사진을 설정하는 코드를 수정하였습니다.
- 로그아웃 코드를 수정하여 로그아웃시 로컬 스토리지에서 프로필, 닉네임, 아이디가 삭제되도록 하였습니다.
- useAuth 코드를 수정하였습니다. 소셜 로그인시에도 isLogin을 true로 설정하도록 하였습니다.
<br />

[MODIFY] 인증번호 로직, 회원가입 완료 페이지, 로그아웃 수정

---

src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx

탈퇴 시 유저 아이디, 닉네임, 프로필을 로컬 스토리지에서 삭제하는 코드를 추가하였습니다.
<br />

[MODIFY] 계정 탈퇴 페이지 코드 일부 수정

---

src/pages/LoginPage/handleSocialLogin.jsx

*소셜 로그인 코드 재수정합니다. 
(소셜 로그인의 경우 머지 후 배포 링크에서만 수정 결과를 확인할 수 있어 pr이 잦은 점 죄송합니다. ㅠㅠ)

[MODIFY] 소셜 로그인 재수정

---

src/pages/LoginPage/handleSocialLogin.jsx

오류 발생이나 중복 계정일 시 5초 후 로그인 페이지로 재연결하는 코드를 추가했습니다.
<br />
<br />

[MODIFY] handleSocialLogin.jsx 타이머, 로그인 페이지 연결 추가

---

src/hooks/useAuth.jsx
src/pages/AddInfoPage/AddInfoPage.jsx
src/pages/SetNicknamePage/SetNicknamePage.jsx
src/route.jsx

- 자체 로그인 후 홈 화면에서 새로고침해야만 제대로 로드되는 문제를 해결했습니다!
<br />

[MODIFY] 콘솔 코드 정리, 자체 로그인 후 홈 화면 새로고침 문제 수정

---

src/components/Feed/FeedItem.jsx

close #127
<br />
- 홈 피드에서 앨범 상세로 넘어가는 경로 수정
<br />

#127 [FIX] 홈 피드에서 앨범 상세로 넘어가는 링크 경로 수정

---

src/components/Chatting/Chatting.jsx
src/components/Chatting/Chatting.style.jsx
src/components/Profile/Profile.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage.style.jsx

close #133
<br />
- 채팅 신고 기능 임시 구현 및 Profile.jsx 리팩터링

[FEAT] 채팅 신고 기능 임시 구현 및 Profile.jsx 리팩터링

---

src/components/Profile/Profile.jsx

close #137
<br />
- useEffect를 조건문 앞으로 이동
<br />

#137 [FIX] Profile 훅 호출 순서 보장

---

src/dummy/data/album.js
src/pages/ExplorePage/ExplorePage.jsx

close #140
<br />
- 탐색 피드 링크에 변경된 라우트 적용
<br />

#140 [FIX] 탐색 피드 Link에 변경된 라우트 적용

---

src/components/Profile/Profile.jsx
src/dummy/data/album.js
src/pages/ExplorePage/ExplorePage.jsx

- 탐색 피드 Link에 변경된 라우트 적용
<br />

[MERGE] 탐색 피드 클릭 시 해당 유저의 앨범 페이지로 이동

---

src/components/Feed/CommentSection.jsx
src/components/Feed/FeedItem.jsx

close #143
<br />
댓글 작성자와 내용이 보이도록 수정
<br />
<br />

댓글 작성자와 내용이 보이도록 수정

---

src/components/Feed/CommentSection.jsx
src/components/Feed/FeedItem.jsx

close #150
<br />
댓글, 대댓글 등록 시 Enter를 눌러도 등록되도록 수정
<br />
<br />

댓글, 대댓글 등록 시 Enter를 눌러도 등록되도록 수정
